### ISSUE TITLE
Latest release `2.0.21` broke entire deploy

### ISSUE THREAD

**Issue by DanBradbury** [sinatra-activerecord/sinatra-activerecord#107]
Went and deployed some minor changes to my sinatra site and had the following pop up in my heroku logs

From my heroku logs
```
2020-12-10T02:34:34.386666+00:00 app[web.1]: bundler: failed to load command: thin (/app/vendor/bundle/ruby/2.6.0/bin/thin)
2020-12-10T02:34:34.400684+00:00 app[web.1]: NameError: uninitialized constant ActiveRecord::ConnectionAdapters::ConnectionSpecification
2020-12-10T02:34:34.400685+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sinatra-activerecord-2.0.21/lib/sinatra/activerecord.rb:25:in `registered'
2020-12-10T02:34:34.400686+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1455:in `block in register'
2020-12-10T02:34:34.400686+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1453:in `each'
2020-12-10T02:34:34.400687+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1453:in `register'
2020-12-10T02:34:34.400687+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1947:in `register'
2020-12-10T02:34:34.400687+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:2008:in `register'
2020-12-10T02:34:34.400688+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sinatra-activerecord-2.0.21/lib/sinatra/activerecord.rb:81:in `<module:Sinatra>'
2020-12-10T02:34:34.400689+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sinatra-activerecord-2.0.21/lib/sinatra/activerecord.rb:10:in `<top (required)>'
2020-12-10T02:34:34.400689+00:00 app[web.1]: /app/web.rb:4:in `require'
2020-12-10T02:34:34.400690+00:00 app[web.1]: /app/web.rb:4:in `<top (required)>'
2020-12-10T02:34:34.400690+00:00 app[web.1]: config.ru:1:in `require'
2020-12-10T02:34:34.400691+00:00 app[web.1]: config.ru:1:in `block in <main>'
2020-12-10T02:34:34.400691+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
2020-12-10T02:34:34.400692+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
2020-12-10T02:34:34.400695+00:00 app[web.1]: config.ru:1:in `new'
2020-12-10T02:34:34.400695+00:00 app[web.1]: config.ru:1:in `<main>'
2020-12-10T02:34:34.400696+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0/lib/rack/adapter/loader.rb:33:in `eval'
2020-12-10T02:34:34.400696+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0/lib/rack/adapter/loader.rb:33:in `load'
2020-12-10T02:34:34.400697+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
2020-12-10T02:34:34.400697+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0/lib/thin/controllers/controller.rb:72:in `start'
2020-12-10T02:34:34.400697+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0/lib/thin/runner.rb:203:in `run_command'
2020-12-10T02:34:34.400698+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0/lib/thin/runner.rb:159:in `run!'
2020-12-10T02:34:34.400698+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0/bin/thin:6:in `<top (required)>'
2020-12-10T02:34:34.400699+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/thin:23:in `load'
2020-12-10T02:34:34.400699+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/thin:23:in `<top (required)>'
2020-12-10T02:34:34.471147+00:00 heroku[web.1]: Process exited with status 1
2020-12-10T02:34:34.505700+00:00 heroku[web.1]: State changed from starting to crashed
```

Was very very confused and wasted a solid 30+ minutes thinking I did something wrong.. turns out `gem 'sinatra-activerecord', '2.0.20'` fixed everything.. little too irritated to dig into the root cause on a patch change causing this but figured everyone should be aware in case they run into a similar issue

**Comment by sbauch** [comment]
+1 facing the same issue on an open source app.

you ought to be able to reproduce using our Deploy to Heroku button - https://github.com/enterprise-oss/osso

can't reproduce outside of our heroku deploys so this got past CI.

**Comment by engineersmnky** [comment]
The immediate resolution is simple change the gem spec from `gem.add_dependency "activerecord", ">= 4.1"` to `gem.add_dependency "activerecord", ">= 4.1", "< 6.1.0"`. The issue here is that 6.1.0 removed `ActiveRecord::ConnectionAdapters::ConnectionSpecification` in favor of what appears to be `PoolConfig` and `PoolConfigManager` but this class does exist up to and including 6.0.34 so until other changes can be made restricting the rails version to 4.1-6.0 should be sufficient

**Comment by cupnoodle** [comment]
Sorry about this, it is exactly like what @engineersmnky said, ActiveRecord 6.1.0 removed `ActiveRecord::ConnectionAdapters::ConnectionSpecification` , which I have used in this commit : https://github.com/sinatra-activerecord/sinatra-activerecord/commit/0b807ab3c5bf081469762c4f12d2b1acae1fdcd9

I will look into fixing this soon

**Comment by cupnoodle** [comment]
I have made a fix for this and pushed a new gem version (2.0.22), would you mind try using this and see if this resolves the issue? thanks

**Comment by richpeck** [comment]
Works well, thank you!
