### ISSUE TITLE
Any docs on how to get gem set up for local development?

### ISSUE THREAD

**Issue by jayroh** [sinatra-activerecord/sinatra-activerecord#76]
Steps to reproduce:

1. clone repo + cd into dir
2. bundle install
3. bundle exec rake =>

```
ActiveRecord::ConnectionNotEstablished:
  No connection pool with 'primary' found.
```

4. bundle exec rake appraisal =>

Runs SOME specs but then fails with:

```
>> BUNDLE_GEMFILE=/Users/joel/Development/sinatra-activerecord/gemfiles/activerecord_4.0.gemfile bundle exec rake                                                                                                                                      [7/557]
/Users/joel/.rbenv/versions/2.4.0/bin/ruby -I/Users/joel/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib:/Users/joel/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-support-3.6.0/lib /Users/joel/.rbenv/versions/2.4.0/lib/ruby/gem
s/2.4.0/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
db/migrate/20170705042613_create_users.rb
-- initialize_schema_migrations_table()
   -> 0.0026s
..F

Failures:

  1) the sinatra extension establishes the connection with a database url
     Failure/Error: ActiveRecord::Base.configurations[environment.to_s] = ActiveRecord::ConnectionAdapters::ConnectionSpecification::ConnectionUrlResolver.new(spec).to_hash

     NameError:
       uninitialized constant ActiveRecord::ConnectionAdapters::ConnectionSpecification::ConnectionUrlResolver
     # ./lib/sinatra/activerecord.rb:55:in `database='
     # ./spec/sinatra/activerecord_spec.rb:34:in `block (2 levels) in <top (required)>'

Finished in 0.1212 seconds (files took 0.76077 seconds to load)
3 examples, 1 failure
```

*** 

Is there a series of steps to get the specs to run reliably?

**Comment by cupnoodle** [comment]
Heya @jayroh , the issue arise because the gem code actually relies on some method that is implemented on ActiveRecord 4.1.  I have since removed support for AR below 4.1, it should work fine now if you clone and run it again, please open another issue if you found another problem, thanks!
